CREATE TABLE IF NOT EXISTS medical_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    patient_name VARCHAR(50),
    doctor_id BIGINT,
    doctor_name VARCHAR(50),
    department_id BIGINT,
    department_name VARCHAR(100),
    hospital_id BIGINT,
    hospital_name VARCHAR(100),
    chief_complaint VARCHAR(500),
    present_illness TEXT,
    past_history TEXT,
    diagnosis VARCHAR(500),
    treatment_plan TEXT,
    prescription TEXT,
    advice TEXT,
    audit_hash VARCHAR(64),
    deleted INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS exam_report (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    patient_name VARCHAR(50),
    doctor_id BIGINT,
    doctor_name VARCHAR(50),
    exam_type VARCHAR(50),
    exam_part VARCHAR(100),
    findings TEXT,
    conclusion VARCHAR(500),
    image_urls TEXT,
    status VARCHAR(20) DEFAULT 'PUBLISHED',
    record_id BIGINT,
    prev_hash VARCHAR(64),
    current_hash VARCHAR(64),
    deleted INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
