CREATE TABLE IF NOT EXISTS referral (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    patient_name VARCHAR(50),
    from_doctor_id BIGINT,
    from_doctor_name VARCHAR(50),
    from_dept_id BIGINT,
    from_dept_name VARCHAR(100),
    from_hospital_id BIGINT,
    from_hospital_name VARCHAR(100),
    to_dept_id BIGINT,
    to_dept_name VARCHAR(100),
    to_hospital_id BIGINT,
    to_hospital_name VARCHAR(100),
    to_doctor_id BIGINT,
    to_doctor_name VARCHAR(50),
    referral_reason VARCHAR(500),
    diagnosis VARCHAR(500),
    attachments TEXT,
    status VARCHAR(20) DEFAULT 'PENDING',
    reject_reason VARCHAR(500),
    feedback TEXT,
    deleted INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
